# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arcjetCV.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class MyLabel(QtWidgets.QLabel):
    newCursorValue = QtCore.pyqtSignal(list)

    def __init__(self, *args):
        super(MyLabel,self).__init__(*args)

    def mouseMoveEvent(self,event):
        self.newCursorValue.emit([event.x(), event.y()])

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(751, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_img = MyLabel(self.frame)
        self.label_img.setGeometry(QtCore.QRect(10, 10, 731, 451))
        self.label_img.setMinimumSize(QtCore.QSize(731, 451))
        self.label_img.setMouseTracking(True)
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.horizontalLayout_8.addWidget(self.frame)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinBox_FrameIndex = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_FrameIndex.setMaximum(100000)
        self.spinBox_FrameIndex.setProperty("value", 0)
        self.spinBox_FrameIndex.setObjectName("spinBox_FrameIndex")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_FrameIndex)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_flowDirection = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_flowDirection.setObjectName("comboBox_flowDirection")
        self.comboBox_flowDirection.addItem("")
        self.comboBox_flowDirection.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_flowDirection)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_filterType = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_filterType.setObjectName("comboBox_filterType")
        self.comboBox_filterType.addItem("")
        self.comboBox_filterType.addItem("")
        self.comboBox_filterType.addItem("")
        self.comboBox_filterType.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_filterType)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.FilterTabs = QtWidgets.QTabWidget(self.groupBox_2)
        self.FilterTabs.setObjectName("FilterTabs")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minHue = QtWidgets.QSpinBox(self.tab_3)
        self.minHue.setMaximum(180)
        self.minHue.setProperty("value", 0)
        self.minHue.setObjectName("minHue")
        self.horizontalLayout_3.addWidget(self.minHue)
        self.maxHue = QtWidgets.QSpinBox(self.tab_3)
        self.maxHue.setMaximum(180)
        self.maxHue.setProperty("value", 121)
        self.maxHue.setObjectName("maxHue")
        self.horizontalLayout_3.addWidget(self.maxHue)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minSaturation = QtWidgets.QSpinBox(self.tab_3)
        self.minSaturation.setMaximum(255)
        self.minSaturation.setProperty("value", 0)
        self.minSaturation.setObjectName("minSaturation")
        self.horizontalLayout_4.addWidget(self.minSaturation)
        self.maxSaturation = QtWidgets.QSpinBox(self.tab_3)
        self.maxSaturation.setMaximum(255)
        self.maxSaturation.setProperty("value", 125)
        self.maxSaturation.setObjectName("maxSaturation")
        self.horizontalLayout_4.addWidget(self.maxSaturation)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minIntensity = QtWidgets.QSpinBox(self.tab_3)
        self.minIntensity.setMaximum(242)
        self.minIntensity.setProperty("value", 150)
        self.minIntensity.setObjectName("minIntensity")
        self.horizontalLayout_2.addWidget(self.minIntensity)
        self.maxIntensity = QtWidgets.QSpinBox(self.tab_3)
        self.maxIntensity.setMaximum(255)
        self.maxIntensity.setProperty("value", 255)
        self.maxIntensity.setObjectName("maxIntensity")
        self.horizontalLayout_2.addWidget(self.maxIntensity)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.FilterTabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.minHue_2 = QtWidgets.QSpinBox(self.tab_4)
        self.minHue_2.setMaximum(180)
        self.minHue_2.setProperty("value", 125)
        self.minHue_2.setObjectName("minHue_2")
        self.horizontalLayout_6.addWidget(self.minHue_2)
        self.maxHue_2 = QtWidgets.QSpinBox(self.tab_4)
        self.maxHue_2.setMaximum(180)
        self.maxHue_2.setProperty("value", 170)
        self.maxHue_2.setObjectName("maxHue_2")
        self.horizontalLayout_6.addWidget(self.maxHue_2)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.minSaturation_2 = QtWidgets.QSpinBox(self.tab_4)
        self.minSaturation_2.setMaximum(255)
        self.minSaturation_2.setProperty("value", 40)
        self.minSaturation_2.setObjectName("minSaturation_2")
        self.horizontalLayout_7.addWidget(self.minSaturation_2)
        self.maxSaturation_2 = QtWidgets.QSpinBox(self.tab_4)
        self.maxSaturation_2.setMaximum(255)
        self.maxSaturation_2.setProperty("value", 80)
        self.maxSaturation_2.setObjectName("maxSaturation_2")
        self.horizontalLayout_7.addWidget(self.maxSaturation_2)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minIntensity_2 = QtWidgets.QSpinBox(self.tab_4)
        self.minIntensity_2.setMaximum(242)
        self.minIntensity_2.setProperty("value", 85)
        self.minIntensity_2.setObjectName("minIntensity_2")
        self.horizontalLayout_5.addWidget(self.minIntensity_2)
        self.maxIntensity_2 = QtWidgets.QSpinBox(self.tab_4)
        self.maxIntensity_2.setMaximum(255)
        self.maxIntensity_2.setProperty("value", 230)
        self.maxIntensity_2.setObjectName("maxIntensity_2")
        self.horizontalLayout_5.addWidget(self.maxIntensity_2)
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_9.addLayout(self.formLayout_4)
        self.FilterTabs.addTab(self.tab_4, "")
        self.verticalLayout_5.addWidget(self.FilterTabs)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.spinBox_FirstGoodFrame = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_FirstGoodFrame.setMaximum(100000)
        self.spinBox_FirstGoodFrame.setProperty("value", 0)
        self.spinBox_FirstGoodFrame.setObjectName("spinBox_FirstGoodFrame")
        self.horizontalLayout_10.addWidget(self.spinBox_FirstGoodFrame)
        self.spinBox_LastGoodFrame = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_LastGoodFrame.setMaximum(100000)
        self.spinBox_LastGoodFrame.setProperty("value", 0)
        self.spinBox_LastGoodFrame.setObjectName("spinBox_LastGoodFrame")
        self.horizontalLayout_10.addWidget(self.spinBox_LastGoodFrame)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_filename = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_filename)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_writeVideo = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_writeVideo.setObjectName("checkBox_writeVideo")
        self.verticalLayout.addWidget(self.checkBox_writeVideo)
        self.checkBox_writeCSV = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_writeCSV.setObjectName("checkBox_writeCSV")
        self.verticalLayout.addWidget(self.checkBox_writeCSV)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.pushButton_process = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_process.setObjectName("pushButton_process")
        self.horizontalLayout.addWidget(self.pushButton_process)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 10, 351, 311))
        self.graphicsView_2.setTabletTracking(False)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.postProcessParams = QtWidgets.QGroupBox(self.tab_2)
        self.postProcessParams.setGeometry(QtCore.QRect(750, 20, 341, 301))
        self.postProcessParams.setObjectName("postProcessParams")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.postProcessParams)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(30, 30, 291, 161))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.spinBox_firstFrame_2 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_firstFrame_2.setMaximum(5000)
        self.spinBox_firstFrame_2.setObjectName("spinBox_firstFrame_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_firstFrame_2)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBox_3 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinBox_4 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_4.setMaximum(10000)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_4)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_flowDirectionPP = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBox_flowDirectionPP.setObjectName("comboBox_flowDirectionPP")
        self.comboBox_flowDirectionPP.addItem("")
        self.comboBox_flowDirectionPP.addItem("")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_flowDirectionPP)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(10, 340, 721, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_3.setGeometry(QtCore.QRect(380, 10, 351, 311))
        self.graphicsView_3.setTabletTracking(False)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.basebar = QtWidgets.QLabel(self.centralwidget)
        self.basebar.setText("")
        self.basebar.setObjectName("basebar")
        self.verticalLayout_4.addWidget(self.basebar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuFilters = QtWidgets.QMenu(self.menuMenu)
        self.menuFilters.setObjectName("menuFilters")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_video = QtWidgets.QAction(MainWindow)
        self.actionLoad_video.setObjectName("actionLoad_video")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Filter = QtWidgets.QAction(MainWindow)
        self.actionSave_Filter.setObjectName("actionSave_Filter")
        self.actionLoad_Filter_2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_Filter_2.setObjectName("actionLoad_Filter_2")
        self.actionSave_Filter_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_Filter_2.setObjectName("actionSave_Filter_2")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFilters.addAction(self.actionLoad_Filter_2)
        self.menuFilters.addAction(self.actionSave_Filter_2)
        self.menuMenu.addAction(self.actionLoad_video)
        self.menuMenu.addAction(self.menuFilters.menuAction())
        self.menuMenu.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.FilterTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Input parameters"))
        self.label_7.setText(_translate("MainWindow", "Frame Index:"))
        self.label_3.setText(_translate("MainWindow", "Flow direction:"))
        self.comboBox_flowDirection.setItemText(0, _translate("MainWindow", "right"))
        self.comboBox_flowDirection.setItemText(1, _translate("MainWindow", "left"))
        self.label_4.setText(_translate("MainWindow", "Filter Method:"))
        self.comboBox_filterType.setItemText(0, _translate("MainWindow", "AutoHSV"))
        self.comboBox_filterType.setItemText(1, _translate("MainWindow", "CNN"))
        self.comboBox_filterType.setItemText(2, _translate("MainWindow", "HSV"))
        self.comboBox_filterType.setItemText(3, _translate("MainWindow", "GRAY"))
        self.label_8.setText(_translate("MainWindow", "Hue (0-180)"))
        self.label_9.setText(_translate("MainWindow", "Saturation (0-255)"))
        self.label_5.setText(_translate("MainWindow", "Value (0-255)"))
        self.FilterTabs.setTabText(self.FilterTabs.indexOf(self.tab_3), _translate("MainWindow", "Model Filter"))
        self.label_15.setText(_translate("MainWindow", "Hue (0-180)"))
        self.label_16.setText(_translate("MainWindow", "Saturation (0-255)"))
        self.label_6.setText(_translate("MainWindow", "Value (0-255)"))
        self.FilterTabs.setTabText(self.FilterTabs.indexOf(self.tab_4), _translate("MainWindow", "Shock Filter"))
        self.groupBox.setTitle(_translate("MainWindow", "Output parameters"))
        self.label_17.setText(_translate("MainWindow", "Frame range:"))
        self.label_20.setText(_translate("MainWindow", "Output filename:"))
        self.checkBox_writeVideo.setText(_translate("MainWindow", "Write video?"))
        self.checkBox_writeCSV.setText(_translate("MainWindow", "Write csv?"))
        self.pushButton_process.setText(_translate("MainWindow", "Process All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Extract Edges"))
        self.postProcessParams.setTitle(_translate("MainWindow", "Post process parameters"))
        self.label_10.setText(_translate("MainWindow", "Frames per second"))
        self.label_11.setText(_translate("MainWindow", "Min model area (%)"))
        self.label_12.setText(_translate("MainWindow", "Model radius"))
        self.label_13.setText(_translate("MainWindow", "Flow direction:"))
        self.comboBox_flowDirectionPP.setItemText(0, _translate("MainWindow", "right"))
        self.comboBox_flowDirectionPP.setItemText(1, _translate("MainWindow", "left"))
        self.label_14.setText(_translate("MainWindow", "Skip index"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Post Process"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuFilters.setTitle(_translate("MainWindow", "Filters"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoad_video.setText(_translate("MainWindow", "Load video"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_Filter.setText(_translate("MainWindow", "Save Filter"))
        self.actionLoad_Filter_2.setText(_translate("MainWindow", "Load Filter"))
        self.actionSave_Filter_2.setText(_translate("MainWindow", "Save Filter"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
